name: S3 Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v2

      - name: AWS認証情報の設定
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # S3バケットのリージョンに合わせて変更

      - name: ビルドスクリプトの実行
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          chmod +x build.sh
          ./build.sh

      - name: S3へのデプロイ
        uses: aws-actions/s3-sync@v1.1.2
        with:
          args: --acl public-read --delete
          bucket: mapit.faanau.co.jp
          local-path: map.html
          exclude: "**/.git/**"

